[package]
name = "efitools"
version = "0.1.0"
authors = ["Nicholas Bishop <nicholasbishop@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
argh = "0.1"
fehler = "1.0"
thiserror = "1.0"
uuid = "0.8"
x509-parser = "0.7"
